### ISSUE TITLE
Will you be selling these?

### ISSUE THREAD

**Issue by nerdguy1338** [joeycastillo/The-Open-Book#11]
I love this concept, but is this a design to hack upon, or plans for a final product that is open hardware?

**Comment by joeycastillo** [comment]
That's a great question, and one for which I don't have a great answer just yet. I can assemble prototypes myself, but that doesn't scale well enough to sell them in any quantity. I guess my vision is that people would build these themselves — you can do it with a stencil, tweezers and [a toaster oven](https://learn.adafruit.com/ez-make-oven?view=all) — but I'm also willing to look into manufacturing. It's not 100% in my wheelhouse, but then neither was PCB design a year ago :)

**Comment by nerdguy1338** [comment]
That's the thing, most of the board you designed is through-hole, except
the feather itself. I've never done surface mount soldering, and I'm not
really comfortable gambling this much money on a kit of parts.

Why is the feather not also through hole?

**Comment by joeycastillo** [comment]
Basically because the e-ink screen is fragile glass, and needs to adhere directly to the the front of the PCB for structural support. Most of the board is surface mount actually, specifically so that the front of the PCB can be a smooth and flat surface for the screen to sit on; all the thru-hole pieces are above and below the screen. 

Totally sympathize though with your concern... I was also very intimidated by surface mount soldering and had to learn some new skills to make this. FWIW except for two tricky parts (the SAMD51 and the 24-pin connector) I chose wide-pitch SOIC chips and 0805 or larger passives, so that it would be as easy as possible to pick and place by hand. It's not as easy as thru-hole, but it's definitely doable, especially if you practice on some simpler surface mount boards to start with.

**Comment by AsherGomez** [comment]
Hey, awesome project! I like that it works with a Feather ecosystem. You should submit it on Hackaday.io for this [contest](https://hackaday.io/contest/168107-take-flight-with-feather) that’s running right now, good luck!

**Comment by nelsonblaha** [comment]
Someone willing and able to make these to-order should name their price here. I think they would be pleasantly surprised at the demand.

**Comment by gromain** [comment]
I believe those could be made by quantities 100 for between 150-200$ piece (complete assembled with casing and shipping).

**Comment by 1094** [comment]
I understand the not wanting to sell completed readers, but have you considered selling kits?

**Comment by joeycastillo** [comment]
It's not the Open Book per se, but I did have a run of the E-Book Featherwing PCB's made, and as of today [they are available on Tindie](https://www.tindie.com/products/joeycastillo/the-e-book-wing-pcb-bare-pcb/). I started with this board since It's simpler to build than the Open Book, and if you pair it with a Feather M4, it works seamlessly with the Open Book Arduino library. Not quite a kit, but the BOM is included as a spreadsheet you can upload to Digikey, and the only other part you'd need is the e-paper display which is [available from Good Display](https://zh-tw.buyepaper.com/42inch-e-ink-panel-spi-interface-buy-e-paper-display-p0085.html).

I imagine I will likely do a similar run with the Open Book PCB at some point, but this is what I have today :)
