### ISSUE TITLE
e paper display sold out

### ISSUE THREAD

**Issue by the-kant-rawls-mafia** [joeycastillo/The-Open-Book#86]
the epaper display recommended on the website that goes with the PCB is sold out. Would this display work:

https://www.good-display.com/product/386.html

???

**Comment by joeycastillo** [comment]
It can work but not with the Abridged Edition. The main difference is it requires a different value of inductor (47uH instead of 10uH). There are [design files here](https://github.com/joeycastillo/The-Open-Book/tree/newscreen/Fabrication%20Files/Open%20Book%20Main%20Board/DO%20NOT%20USE%20YET) that work with this display, but I’ve labeled them as not for use yet because I haven’t fully fleshed out the display driver. It works, but we don’t have partial refresh or grayscale mode yet.

**Comment by Silent-Hunter** [comment]
What happens if you don't have partial refresh or greyscale mode? If the book only works with plaintext files, wouldn't those things not be needed? Please pardon my ignorance.

**Comment by Kuratius** [comment]
Partial refresh and greyscale can be added retroactively if you can edit the waveform data inside the display. Even black and white displays have at least 4 waveforms available that you can use.
Otherwise yes you'd have to live with black/white, dithering and having the entire display update just to change 1 pixel.

**Comment by joeycastillo** [comment]
Partial refresh is pretty crucial to having a responsive UI. Like when selecting a book, waiting a full second between pressing a button and moving the focus one row is not delightful. Whereas with partial refresh it’s a lot quicker. It’s definitely solvable, just no longer an area of focus for me since this is a design I never shipped or recommended that folks try and build.

**Comment by Silent-Hunter** [comment]
Well unfortunately the display you designed for is unavailable anywhere, I think it's been discontinued. So not having partial refresh is definitely preferable to not having an Open Book at all. Is there another display you had in mind?

**Comment by Kuratius** [comment]
For what it's worth, except for the size a pimoroni badger 2040 has essentially the same functionality as what you would get from the open book, just a smaller screen size. You need a special driver to get greyscale, though. If you were looking to write software that can later be used with the open book, this would be a good candidate. It also avoids having to do your own assembly. (Also someone should really tell pimoroni to get on with making an eink device that is a bigger size- they already made the inkys with colour eink, a bigger size with faster refresh but black/white as an ereader wouldn't be a bad thing)
 https://shop.pimoroni.com/products/badger-2040-w?variant=40514062188627

The PineNote got a new batch in December, if you're more looking for an ereader that can run koreader and custom kernels and whatnot, but it's quite a bit bigger than the open book.

There are older kobos that can run custom software like QuillOS or postmarketOS and some of the linux-based pocketbook readers have an sdk.

**Comment by Silent-Hunter** [comment]
Definitely some interesting ideas. I really want something that can use standard AA or AAA batteries, that way I can just swap them when they get low, and easily replace them when they stop reacharging. That's one of the things that really drew me to this project.

**Comment by Kuratius** [comment]
Badger2040 uses AA batteries I think.

**Comment by Silent-Hunter** [comment]
Yeah I looked at it, but the screen is just too low res for a book I think.
